// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TermProject.Models;

#nullable disable

namespace TermProject.Migrations
{
    [DbContext(typeof(SportLeagueContext))]
    [Migration("20240927235034_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TermProject.Models.Members", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryOrgin")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadQuarters")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Membership");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Division = "1",
                            Email = "EPL@eng.com",
                            HeadQuarters = "1099 way",
                            LeagueName = "English premire league",
                            Sport = "Soccer"
                        },
                        new
                        {
                            ID = 2,
                            Division = "1",
                            Email = "NFL@yahoo.com",
                            HeadQuarters = "1023 my drive",
                            LeagueName = "NFL",
                            Sport = "FootBall"
                        },
                        new
                        {
                            ID = 3,
                            Division = "1",
                            Email = "MLB@gmail.com",
                            HeadQuarters = "328 west hollywood",
                            LeagueName = "MLB",
                            Sport = "Baseball"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
